# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'blacklist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for blacklist
  pod 'RealmSwift'
  pod 'SwiftLint'

  target 'blacklistTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
